```{r}
# Access remote GizmoSQL tables as dbplyr dataframes (which transparently transform most dplyr/tidy manipulations to SQL)

library(tidyverse)
db_params <- yaml::read_yaml(here::here("db_secret.yaml"))

con <- DBI::dbConnect(
  adbi::adbi("adbcflightsql::adbcflightsql"),
  uri = db_params$uri,
  username = db_params$username,
  password = db_params$password
)

tbl(con, dbplyr::in_schema("books","all_years_of_publication")) |> 
  filter(year_of_publication>=1400, year_of_publication<=2030) |>
  count(year_of_publication) |>
  arrange(desc(n)) |>
  explain()

tbl(con, dbplyr::in_schema("books","all_years_of_publication")) |> 
  filter(year_of_publication>=1400, year_of_publication<=2030) |>
  count(year_of_publication) |>
  arrange(desc(n))
```


```{r}
# The common_basis.R helper registers all remote tables as dbplyr objects
options(box.path = here::here(""))
box::use(src/common_basis)
rlang::env_coalesce(box::topenv(), common_basis)
library(tidyverse)
library(gghsci)
```

```{r}
all_years_of_publication |>
  filter(year_of_publication>=1400, year_of_publication<=2030) |>
  count(year_of_publication) |>
  ggplot(aes(x=year_of_publication, y=n)) + 
  geom_line() +
  theme_hsci()
```

